### ISSUE TITLE
Deliverable Checklist for Dec 15th 2019

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/hotel-website-vkirirom.com#205]
- [ ] i18n multi language support (+ Khmer)
- [ ] Search page changes (better landing page), as well as other design spit shines
- [ ] "my account" page addition
- [ ] automated email receipt after booking OR form fill
- [ ] CMS to publish/edit new pages (low priority, may miss our deadline on this since it requires lots of backend work)

## i18n multi language support (+ Khmer)
https://github.com/whynotearth/meredith-core/issues/20
translation is done, text is on page. But we need to do backend work to make the tables happen (scheduled in two weeks to be completed by Will). Then redo the databases to reflect the changes, and tie the language change icon up (front end).

## Search page changes (better landing page), as well  as other design spit shines
https://github.com/whynotearth/hotel-website-vkirirom.com/issues/188

change the /search/ landing page to be better, fairly simple front end task

## "my account" page addition
https://github.com/whynotearth/hotel-website-vkirirom.com/issues/204

*Probably* going to require extensive backend work, need to get designs to front end team and talk this over/task it out

## automated email receipt after booking OR form fill
https://github.com/whynotearth/hotel-website-vkirirom.com/issues/173
best practice would say send email via backend, but may do front end. Webhook could be an easy solution for this quickly.

## CMS to publish/edit new pages
low priority, need to get designs done and timeline this out. possibly consider https://www.storyblok.com/
